// https://bdsm-test.info/result.html?ver=0.03&gender=male&age=2022&sexual=hef&MT=16&HU=13&BT=15&OW=14&DM=17&DG=17&DO=18&VA=-5&RB=-2&PR=0&SL=1&BR=2&PE=3&LI=4&MA=5&SK=6&SA=7&SU=8&RI=9&SP=10&DE=11&SW=12&
export const exam = [
  {
    id: '1',
    문제: 'BDSM은 무엇의 약자인가요?',
    선택지: [
      { id: '1', label: 'Bondage, Discipline, Sadism, Masochism' },
      { id: '2', label: 'Beautiful Dream, Simple Mind' },
      { id: '3', label: 'Bold Decision, Silent Movement' },
      { id: '4', label: 'Basic, Dynamic, Stable, Mingle' },
    ],
    정답: ['1'],
  },
  {
    id: '2',
    문제: "BDSM의 'Bondage'는 무엇을 의미하는가요?",
    선택지: [
      { id: '1', label: '구속' },
      { id: '2', label: '징계' },
      { id: '3', label: '슬픔' },
      { id: '4', label: '동정' },
      { id: '5', label: '지배' },
      { id: '6', label: '굴복' },
    ],
    정답: ['1'],
  },
  {
    id: '3',
    문제: "BDSM 활동에서 'safe word'는 무엇을 위한 것인가요?",
    선택지: [
      { id: '1', label: '활동을 즉시 중단시키기 위해' },
      { id: '2', label: '상대방을 더 힘들게 만들기 위해' },
      { id: '3', label: '더 강한 통증을 요청하기 위해' },
      { id: '4', label: '상대방을 격려하기 위해' },
    ],
    정답: ['1'],
  },
  {
    id: '4',
    문제: 'BDSM 활동에 참여하는 이들이 주로 신경 써야 하는 원칙은 무엇인가요?',
    선택지: [
      { id: '1', label: '동의' },
      { id: '2', label: '비밀유지' },
      { id: '3', label: '힘의 발휘' },
      { id: '4', label: '통제 불능' },
    ],
    정답: ['1'],
  },
  {
    id: '5',
    문제: 'BDSM에서 SSC는 무엇을 의미하는가요?',
    선택지: [
      { id: '1', label: 'Safe, Sane, Consensual' },
      { id: '2', label: 'Super Sensual Connection' },
      { id: '3', label: 'Strict, Strong, Controllable' },
      { id: '4', label: 'Silent, Secret, Cautious' },
    ],
    정답: ['1'],
  },
  {
    id: '6',
    문제: "BDSM의 'Discipline'은 무엇을 의미하는가?",
    선택지: [
      { id: '1', label: '규율 및 훈육' },
      { id: '2', label: '인내와 끈기' },
      { id: '3', label: '의사 결정의 자유' },
      { id: '4', label: '금욕' },
    ],
    정답: ['1'],
  },
  {
    id: '7',
    문제: 'RACK 원칙은 무엇을 의미하는가?',
    선택지: [
      { id: '1', label: 'Risk Accepted Consensual Kink' },
      { id: '2', label: 'Rigidly Administered Control Knowledge' },
      { id: '3', label: 'Reserved Act of Conscious Knowledge' },
      { id: '4', label: 'Relational Aesthetics of Consensual Kink' },
    ],
    정답: ['1'],
  },
  {
    id: '8',
    문제: 'BDSM 활동 중, 교육과 훈련을 주로 담당하는 역할은 무엇인가요?',
    선택지: [
      { id: '1', label: 'Master/Mistress' },
      { id: '2', label: 'Switch' },
      { id: '3', label: 'Slave' },
      { id: '4', label: 'Spectator' },
    ],
    정답: ['1'],
  },
  {
    id: '9',
    문제: "'Impact play'는 주로 무엇을 포함하나요?",
    선택지: [
      { id: '1', label: '체벌과 타격' },
      { id: '2', label: '경제적 영향' },
      { id: '3', label: '정신적 영향' },
      { id: '4', label: '명상과 집중' },
    ],
    정답: ['1'],
  },
  {
    id: '10',
    문제: "'Aftercare'는 BDSM 활동 후에 어떤 목적으로 이루어지나요?",
    선택지: [
      { id: '1', label: '참여자의 물리적, 정신적 복구를 돕기 위해' },
      { id: '2', label: '활동의 효과를 강화시키기 위해' },
      { id: '3', label: '경험을 바탕으로 다음 활동을 계획하기 위해' },
      { id: '4', label: '새로운 활동을 즉시 시작하기 위해' },
    ],
    정답: ['1'],
  },
  {
    id: '11',
    문제: "BDSM에서 'subspace'는 무엇을 가리키는 용어인가요?",
    선택지: [
      { id: '1', label: '서브가 재미와 행복을 느끼는 정신적 상태' },
      { id: '2', label: '서브가 활동을 거부하는 정신적 공간' },
      { id: '3', label: '서브가 돔에게 권력을 넘기는 과정' },
      { id: '4', label: '돔과 서브가 공유하는 물리적 공간' },
    ],
    정답: ['1'],
  },
  {
    id: '12',
    문제: "'Consent'이 BDSM에서 중요한 이유는 무엇인가요?",
    선택지: [
      { id: '1', label: '참여자 모두의 안전과 존중을 보장하기 위해' },
      { id: '2', label: '법적 문제를 피하기 위해' },
      { id: '3', label: '상대방을 통제하기 위해' },
      { id: '4', label: '활동의 질을 향상시키기 위해' },
    ],
    정답: ['1'],
  },
  {
    id: '13',
    문제: "BDSM에서 'Dom'의 역할은 무엇인가요?",
    선택지: [
      { id: '1', label: '명령과 통제를 수행' },
      { id: '2', label: '구속과 제약을 받음' },
      { id: '3', label: '서비스와 순종을 제공' },
      { id: '4', label: '관찰하고 학습함' },
    ],
    정답: ['1'],
  },
  {
    id: '14',
    문제: "BDSM에서 'Edgeplay'는 무엇을 의미하나요?",
    선택지: [
      { id: '1', label: '경계를 테스트하는 위험한 활동' },
      { id: '2', label: '서브의 통증 한계를 시험' },
      { id: '3', label: '돔의 지배력을 최대화하는 활동' },
      { id: '4', label: '참여자의 능력과 기술을 향상시키는 연습' },
    ],
    정답: ['1'],
  },
  {
    id: '15',
    문제: "'Hard limit'는 무엇을 의미하는 용어인가요?",
    선택지: [
      { id: '1', label: '플레이 참여자가 절대로 넘어서지 않을 경계' },
      { id: '2', label: '서브가 물리적으로 견딜 수 있는 한계' },
      { id: '3', label: '돔의 지배 영역' },
      { id: '4', label: '플레이 중 발생할 수 있는 최대 통증' },
    ],
    정답: ['1'],
  },
  {
    id: '16',
    문제: "BDSM에서 'switch'는 무엇을 의미하나요?",
    선택지: [
      { id: '1', label: '돔과 서브 역할 사이를 전환할 수 있는 사람' },
      { id: '2', label: '상대방의 역할을 전환시킬 수 있는 사람' },
      { id: '3', label: '전원을 끄는 행위' },
      { id: '4', label: '기기 또는 도구의 사용' },
    ],
    정답: ['1'],
  },
  {
    id: '17',
    문제: "'Collaring'은 무엇을 나타내나요?",
    선택지: [
      { id: '1', label: '서브에게 목걸이를 주어 소유권과 헌신을 나타내는 행위' },
      { id: '2', label: '서브에게 특정 행위를 훈련하는 과정' },
      { id: '3', label: '서브를 끈에 묶는 행위' },
      { id: '4', label: '서브를 격리하는 행위' },
    ],
    정답: ['1'],
  },
  {
    id: '18',
    문제: '어떤 용어가 BDSM 플레이에서의 물리적, 정신적 안전을 확인하는 질문의 형태를 나타내나요?',
    선택지: [
      { id: '1', label: 'Check-in' },
      { id: '2', label: 'Safety call' },
      { id: '3', label: 'Green light' },
      { id: '4', label: 'Safe zone' },
    ],
    정답: ['1'],
  },
  {
    id: '19',
    문제: "'Safeword'의 예로 가장 적절하지 않은 것은 무엇인가요?",
    선택지: [
      { id: '1', label: '계속' },
      { id: '2', label: '빨강' },
      { id: '3', label: '팽이' },
      { id: '4', label: '중단' },
    ],
    정답: ['1'],
  },
  {
    id: '20',
    문제: "BDSM 플레이 중 '묶임'에 관련된 용어는 무엇인가요?",
    선택지: [
      { id: '1', label: 'Bondage' },
      { id: '2', label: 'Spanking' },
      { id: '3', label: 'Flogging' },
      { id: '4', label: 'Humiliation' },
    ],
    정답: ['1'],
  },
  {
    id: '21',
    문제: "BDSM에서 'scene'이라는 용어는 무엇을 의미하나요?",
    선택지: [
      { id: '1', label: '특정 BDSM 활동 또는 장면' },
      { id: '2', label: '커뮤니티 또는 클럽' },
      { id: '3', label: '돔과 서브의 관계' },
      { id: '4', label: '가상의 판타지' },
    ],
    정답: ['1'],
  },
  {
    id: '22',
    문제: "BDSM 활동에서 'negotiation'은 왜 중요한가요?",
    선택지: [
      { id: '1', label: '규칙과 한계, 동의 등을 논의하기 위해' },
      { id: '2', label: '가격을 정하기 위해' },
      { id: '3', label: '판타지를 공유하기 위해' },
      { id: '4', label: '돔의 권한을 확립하기 위해' },
    ],
    정답: ['1'],
  },
  {
    id: '23',
    문제: '무엇이 서브와 돔 간의 균형을 나타내는 주요 요소인가요?',
    선택지: [
      { id: '1', label: '권한 교환' },
      { id: '2', label: '물리적 힘' },
      { id: '3', label: '재무적 권한' },
      { id: '4', label: '성적 지배' },
    ],
    정답: ['1'],
    해설: "'성적 지배'는 BDSM에서 중요한 요소 중 하나이며, 많은 사람들이 BDSM을 탐험하는 주요 동기 중 하나일 수 있습니다. 그러나, 서브와 돔 간의 관계는 단순히 성적 지배에만 국한되지 않습니다. 이 관계의 핵심은 '권한 교환'입니다. '권한 교환'은 서브가 일정한 시간 동안 돔에게 일정량의 권한을 자발적으로 양도하는 것을 의미합니다. 이 교환은 서브의 동의와 안전한 환경에서 이루어지며, 둘 사이의 균형을 유지하는 데 중요합니다. 성적 지배는 권한 교환의 한 형태일 수 있지만, 그것만이 BDSM의 전부는 아닙니다. 물론, BDSM에는 다양한 플레이와 다양한 선호도가 있기 때문에, 일부 커플은 성적 지배를 그들의 관계의 핵심으로 여길 수 있습니다. 그러나 일반적으로 서브와 돔 간의 관계의 핵심은 권한의 교환입니다.",
  },
  {
    id: '24',
    문제: "BDSM에서 'soft limit'은 무엇을 의미하나요?",
    선택지: [
      { id: '1', label: '넘어서면 안 되지만 탐색이 가능한 경계' },
      { id: '2', label: '경계를 넘어서는 것이 절대로 허용되지 않는 것' },
      { id: '3', label: '약한 제한 또는 규칙' },
      { id: '4', label: '서브의 물리적인 한계' },
    ],
    정답: ['1'],
  },
  {
    id: '25',
    문제: "BDSM에서 'chastity'는 어떤 행위와 가장 관련이 깊은가요?",
    선택지: [
      { id: '1', label: '돔에 의한 서브의 성적 통제' },
      { id: '2', label: '순결과 청결을 유지하는 행위' },
      { id: '3', label: '체벌과 규율' },
      { id: '4', label: '안전한 플레이를 위한 규칙 설정' },
    ],
    정답: ['1'],
  },
  {
    id: '',
    문제: '',
    선택지: [
      { id: '1', label: '' },
      { id: '2', label: '' },
      { id: '3', label: '' },
      { id: '4', label: '' },
    ],
    정답: ['1'],
  },
  {
    id: '',
    문제: '',
    선택지: [
      { id: '1', label: '' },
      { id: '2', label: '' },
      { id: '3', label: '' },
      { id: '4', label: '' },
    ],
    정답: ['1'],
  },
  {
    id: '',
    문제: '',
    선택지: [
      { id: '1', label: '' },
      { id: '2', label: '' },
      { id: '3', label: '' },
      { id: '4', label: '' },
    ],
    정답: ['1'],
  },
  {
    id: '',
    문제: '',
    선택지: [
      { id: '1', label: '' },
      { id: '2', label: '' },
      { id: '3', label: '' },
      { id: '4', label: '' },
    ],
    정답: ['1'],
  },
  {
    id: '',
    문제: '',
    선택지: [
      { id: '1', label: '' },
      { id: '2', label: '' },
      { id: '3', label: '' },
      { id: '4', label: '' },
    ],
    정답: ['1'],
  },
  {
    id: '',
    문제: '',
    선택지: [
      { id: '1', label: '' },
      { id: '2', label: '' },
      { id: '3', label: '' },
      { id: '4', label: '' },
    ],
    정답: ['1'],
  },
  {
    id: '',
    문제: '',
    선택지: [
      { id: '1', label: '' },
      { id: '2', label: '' },
      { id: '3', label: '' },
      { id: '4', label: '' },
    ],
    정답: ['1'],
  },
  {
    id: '',
    문제: '',
    선택지: [
      { id: '1', label: '' },
      { id: '2', label: '' },
      { id: '3', label: '' },
      { id: '4', label: '' },
    ],
    정답: ['1'],
  },
  {
    id: '',
    문제: '',
    선택지: [
      { id: '1', label: '' },
      { id: '2', label: '' },
      { id: '3', label: '' },
      { id: '4', label: '' },
    ],
    정답: ['1'],
  },
  {
    id: '',
    문제: '',
    선택지: [
      { id: '1', label: '' },
      { id: '2', label: '' },
      { id: '3', label: '' },
      { id: '4', label: '' },
    ],
    정답: ['1'],
  },
  {
    id: '',
    문제: '',
    선택지: [
      { id: '1', label: '' },
      { id: '2', label: '' },
      { id: '3', label: '' },
      { id: '4', label: '' },
    ],
    정답: ['1'],
  },
  {
    id: '',
    문제: '',
    선택지: [
      { id: '1', label: '' },
      { id: '2', label: '' },
      { id: '3', label: '' },
      { id: '4', label: '' },
    ],
    정답: ['1'],
  },
  {
    id: '',
    문제: '',
    선택지: [
      { id: '1', label: '' },
      { id: '2', label: '' },
      { id: '3', label: '' },
      { id: '4', label: '' },
    ],
    정답: ['1'],
  },
  {
    id: '',
    문제: '',
    선택지: [
      { id: '1', label: '' },
      { id: '2', label: '' },
      { id: '3', label: '' },
      { id: '4', label: '' },
    ],
    정답: ['1'],
  },
  {
    id: '',
    문제: '',
    선택지: [
      { id: '1', label: '' },
      { id: '2', label: '' },
      { id: '3', label: '' },
      { id: '4', label: '' },
    ],
    정답: ['1'],
  },
  {
    id: '',
    문제: '',
    선택지: [
      { id: '1', label: '' },
      { id: '2', label: '' },
      { id: '3', label: '' },
      { id: '4', label: '' },
    ],
    정답: ['1'],
  },
  {
    id: '',
    문제: '',
    선택지: [
      { id: '1', label: '' },
      { id: '2', label: '' },
      { id: '3', label: '' },
      { id: '4', label: '' },
    ],
    정답: ['1'],
  },
  {
    id: '',
    문제: '',
    선택지: [
      { id: '1', label: '' },
      { id: '2', label: '' },
      { id: '3', label: '' },
      { id: '4', label: '' },
    ],
    정답: ['1'],
  },
  {
    id: '',
    문제: '',
    선택지: [
      { id: '1', label: '' },
      { id: '2', label: '' },
      { id: '3', label: '' },
      { id: '4', label: '' },
    ],
    정답: ['1'],
  },
  {
    id: '',
    문제: '',
    선택지: [
      { id: '1', label: '' },
      { id: '2', label: '' },
      { id: '3', label: '' },
      { id: '4', label: '' },
    ],
    정답: ['1'],
  },
  {
    id: '',
    문제: '',
    선택지: [
      { id: '1', label: '' },
      { id: '2', label: '' },
      { id: '3', label: '' },
      { id: '4', label: '' },
    ],
    정답: ['1'],
  },
]
